#include<iostream.h>
#include<conio.h>
#include<math.h>

void main()
{
clrscr();

int x,y,z,w,a;

cout<<"Choose any number between 1 to 9, and tell me the number, when subtracted by 10: ";
cin>>y;

cout<<"Now, multiply your number by 2 and spit it out: ";
cin>>z;

cout<<"Now again, multiply your number with 5 and spit it out like a BIHARI! : ";
cin>>w;

cout<<"And lastly, devide your number with 10 and give me the answer: ";
cin>>a;

cout<<"Then your number was: "<<10-y;


getch();
}




